/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.edu.javeriana.fdb.view;

import co.edu.javeriana.fdb.parcialdb.model.dto.DepartamentoDTO;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author Andres
 */
public class DepartamentoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DepartamentoJPanel
     */
    private final Principal principal;
    public DepartamentoJPanel(Principal principal) {
        initComponents();
        this.principal = principal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        BotonMenu = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        BotonCrear = new javax.swing.JButton();
        BotonEdit = new javax.swing.JButton();
        BotonEliminar = new javax.swing.JButton();
        BotonBuscar = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BoxCode = new javax.swing.JTextField();
        BoxNombre = new javax.swing.JTextField();
        BoxPresupuesto = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        jLabel1.setText("Departamento");

        jLabel2.setText("Departamentos:");

        jLabel3.setText("Codigo del departamento:");

        jLabel4.setText("Nombre:");

        jLabel5.setText("Presupuesto:");

        BotonMenu.setBackground(new java.awt.Color(255, 255, 255));
        BotonMenu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonMenu.setText("Menu");
        BotonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMenuActionPerformed(evt);
            }
        });

        BotonSalir.setBackground(new java.awt.Color(204, 0, 0));
        BotonSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonSalir.setForeground(new java.awt.Color(255, 255, 255));
        BotonSalir.setText("Salir");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        BotonCrear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonCrear.setText("Crear");
        BotonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCrearActionPerformed(evt);
            }
        });

        BotonEdit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonEdit.setText("Editar");
        BotonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEditActionPerformed(evt);
            }
        });

        BotonEliminar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonEliminar.setText("Eliminar");
        BotonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarActionPerformed(evt);
            }
        });

        BotonBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonBuscar.setText("Buscar");
        BotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Code", "Nombre", "Presupuesto"
            }
        ));
        jScrollPane6.setViewportView(jTable1);

        BoxCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxCodeActionPerformed(evt);
            }
        });

        BoxNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxNombreActionPerformed(evt);
            }
        });

        BoxPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxPresupuestoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(49, 49, 49)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(BoxCode, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel5))
                                            .addGap(65, 65, 65)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(BoxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(BoxPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(jSeparator2)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(15, 15, 15)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(BotonCrear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotonEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotonEliminar)
                        .addGap(10, 10, 10)
                        .addComponent(BotonBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(BotonMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotonSalir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(BoxCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoxPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonCrear)
                    .addComponent(BotonEdit)
                    .addComponent(BotonEliminar)
                    .addComponent(BotonBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonMenu)
                    .addComponent(BotonSalir))
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMenuActionPerformed
        this.principal.DepartamentoMenu();
    }//GEN-LAST:event_BotonMenuActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        this.principal.salir();
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void BotonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEditActionPerformed
        DepartamentoDTO Depa;
        if(!WhiteSpace()){
            Depa = new DepartamentoDTO(this.BoxCode.getText(),this.BoxNombre.getText(),Float.parseFloat(this.BoxPresupuesto.getText()));
            if(this.principal.CrearDep(Depa)){
                JOptionPane.showMessageDialog(null,"Departamento actualizado!");
            }else{
                JOptionPane.showMessageDialog(null,"No se actualizo!");
            }
            refresh();
        }
    }//GEN-LAST:event_BotonEditActionPerformed

    private void BoxCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxCodeActionPerformed

    private void BoxNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxNombreActionPerformed

    private void BoxPresupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxPresupuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxPresupuestoActionPerformed

    private void BotonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCrearActionPerformed
        DepartamentoDTO Dep;
        if(!WhiteSpace()){
            Dep = new DepartamentoDTO(this.BoxCode.getText(),this.BoxNombre.getText(),Float.parseFloat(this.BoxPresupuesto.getText()));
            if(this.principal.EditDep(Dep)){
                JOptionPane.showMessageDialog(null,"Departamento creado correctamente!");
            }else{
                JOptionPane.showMessageDialog(null,"Ningun campo debe estar vacio!");
            }
            refresh();
        }
    }//GEN-LAST:event_BotonCrearActionPerformed

    private void BotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarActionPerformed
        if(this.BoxCode.getText().equals("")){
            JOptionPane.showMessageDialog(null,"El campo del codigo no puede estar vacio!");
        }else{
            if(this.principal.EliminarDep(this.BoxCode.getText()))
                JOptionPane.showMessageDialog(null,"Departamento eliminado!");
            else
            JOptionPane.showMessageDialog(null,"No se pudo eliminar el departamento. Verifique que existe!");
        }
        refresh();
    }//GEN-LAST:event_BotonEliminarActionPerformed

    private void BotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarActionPerformed
        DepartamentoDTO Dep;
        if(this.BoxCode.getText().equals("")){
            refresh();
        }else{
            Dep = new DepartamentoDTO(this.BoxCode.getText(),this.BoxNombre.getText(),Float.parseFloat(this.BoxPresupuesto.getText()));
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            int F= jTable1.getRowCount();
            for(int i=0;F>i;i++){
                model.removeRow(0);
            }
            if(Dep != null)
                model.addRow(new Object[]{Dep.getCodedep(),Dep.getNombredep(),Dep.getPresupuesto()});
            else
                JOptionPane.showMessageDialog(null, "No se enontro el departamento buscado!");
        }
    }//GEN-LAST:event_BotonBuscarActionPerformed
    private Boolean WhiteSpace(){
        return(this.BoxCode.getText().equals("") || this.BoxNombre.getText().equals("") || this.BoxPresupuesto.getText().equals(""));
    }
    protected void refresh(){
        List<DepartamentoDTO> Dep = this.principal.findAllDep();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        int F=jTable1.getRowCount();
        for(int i = 0; F>i; i++)
            model.removeRow(0);
        if (Dep != null)
            for (DepartamentoDTO De: Dep)
                model.addRow(new Object[]{De.getCodedep(),De.getNombredep(),De.getPresupuesto()});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JButton BotonCrear;
    private javax.swing.JButton BotonEdit;
    private javax.swing.JButton BotonEliminar;
    private javax.swing.JButton BotonMenu;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JTextField BoxCode;
    private javax.swing.JTextField BoxNombre;
    private javax.swing.JTextField BoxPresupuesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
