/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.edu.javeriana.fdb.view;

import co.edu.javeriana.fdb.parcialdb.model.dto.PaisDTO;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

public class PaisJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PaisJPanel
     */
    private final Principal principal;
    public PaisJPanel(Principal principal) {
        initComponents();

        this.principal = principal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        BotonCrear = new javax.swing.JButton();
        BotonEdit = new javax.swing.JButton();
        BotonEliminar = new javax.swing.JButton();
        BotonBuscar = new javax.swing.JButton();
        BotonMenu = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BoxNombre = new javax.swing.JTextField();
        BoxImpuCon = new javax.swing.JTextField();
        BoxImpuTu = new javax.swing.JTextField();
        BoxIVA = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        jLabel1.setText("PAIS");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Impuesto al consumo:");

        jLabel4.setText("Impuesto al turismo:");

        jLabel5.setText("IVA:");

        jLabel6.setText("Paises:");

        BotonCrear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonCrear.setText("Crear");
        BotonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCrearActionPerformed(evt);
            }
        });

        BotonEdit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonEdit.setText("Editar");
        BotonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEditActionPerformed(evt);
            }
        });

        BotonEliminar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonEliminar.setText("Eliminar");
        BotonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarActionPerformed(evt);
            }
        });

        BotonBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonBuscar.setText("Buscar");
        BotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarActionPerformed(evt);
            }
        });

        BotonMenu.setBackground(new java.awt.Color(255, 255, 255));
        BotonMenu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonMenu.setText("Menu");
        BotonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMenuActionPerformed(evt);
            }
        });

        BotonSalir.setBackground(new java.awt.Color(204, 0, 0));
        BotonSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonSalir.setForeground(new java.awt.Color(255, 255, 255));
        BotonSalir.setText("Salir");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "I Consumo", "I turismo", "IVA"
            }
        ));
        jScrollPane6.setViewportView(jTable1);

        BoxNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxNombreActionPerformed(evt);
            }
        });

        BoxImpuCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxImpuConActionPerformed(evt);
            }
        });

        BoxImpuTu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxImpuTuActionPerformed(evt);
            }
        });

        BoxIVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxIVAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(jLabel2)
                                        .addGap(82, 82, 82))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3))
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BoxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BoxImpuCon, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BoxImpuTu, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BoxIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BotonMenu)
                                        .addGap(38, 38, 38)
                                        .addComponent(BotonSalir))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BotonCrear)
                                        .addGap(18, 18, 18)
                                        .addComponent(BotonEdit)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BotonEliminar)))
                                .addGap(18, 18, 18)
                                .addComponent(BotonBuscar)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(BoxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(BoxImpuCon, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoxImpuTu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoxIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonCrear)
                    .addComponent(BotonEdit)
                    .addComponent(BotonEliminar)
                    .addComponent(BotonBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonMenu)
                    .addComponent(BotonSalir))
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        this.principal.salir();
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void BotonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMenuActionPerformed
        this.principal.PaisMenu();
    }//GEN-LAST:event_BotonMenuActionPerformed

    private void BotonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCrearActionPerformed
        PaisDTO Pais;
        if(!WhiteSpace()){
            Pais = new PaisDTO(this.BoxNombre.getText(), Float.parseFloat(this.BoxImpuCon.getText()),Float.parseFloat(this.BoxImpuTu.getText()),Float.parseFloat(this.BoxIVA.getText()));
            if(this.principal.CrearPais(Pais)) JOptionPane.showMessageDialog(null, "Pais creado!");
            else JOptionPane.showMessageDialog(null,"Ningun campo puede estar vacio!");
            refresh();
        }
    }//GEN-LAST:event_BotonCrearActionPerformed

    private void BotonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEditActionPerformed
        PaisDTO Pais;
        if(!WhiteSpace()){
            Pais = new PaisDTO(this.BoxNombre.getText(), Float.parseFloat(this.BoxImpuCon.getText()),Float.parseFloat(this.BoxImpuTu.getText()),Float.parseFloat(this.BoxIVA.getText()));
            if(this.principal.editPais(Pais))
                JOptionPane.showMessageDialog(null, "Pais actualizado!");
            else JOptionPane.showMessageDialog(null,"No se actualizo!");
            refresh();
        }
    }//GEN-LAST:event_BotonEditActionPerformed

    private void BotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarActionPerformed
        if(this.BoxNombre.getText().equals(""))
            JOptionPane.showMessageDialog(null,"El campo nombre no puede estar vacio");
            else
                if(this.principal.eliminarPais(this.BoxNombre.getText()))
                    JOptionPane.showMessageDialog(null, "Pais eliminado!");
                else
                JOptionPane.showMessageDialog(null, "No se pudo eliminar el pais. Verifique que existe");
            refresh();
    }//GEN-LAST:event_BotonEliminarActionPerformed

    private void BotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarActionPerformed
        PaisDTO Pais;
        if(this.BoxNombre.getText().equals("")) refresh();
        else{
            Pais = this.principal.findPais(this.BoxNombre.getText());
            DefaultTableModel model  = (DefaultTableModel) jTable1.getModel();
            int F = jTable1.getRowCount();
            for(int i =0; F>i;i++)
                model.removeRow(0);

            if(Pais != null)
                model.addRow(new Object[]{Pais.getNombre(),Pais.getImpcon(),Pais.getInTur(),Pais.getIva()});
            else
                JOptionPane.showMessageDialog(null, "No se encontro el pais buscado!");
        }
    }//GEN-LAST:event_BotonBuscarActionPerformed

    private void BoxNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxNombreActionPerformed

    private void BoxImpuConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxImpuConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxImpuConActionPerformed

    private void BoxImpuTuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxImpuTuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxImpuTuActionPerformed

    private void BoxIVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxIVAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxIVAActionPerformed

    protected void refresh(){
        List<PaisDTO> Pais = this.principal.findAllPais();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        int F= jTable1.getRowCount();
        for(int i = 0; F>i;i++)
            model.removeRow(0);

        if(Pais != null)
            for(PaisDTO Pa: Pais)
                model.addRow(new Object[]{Pa.getNombre(),Pa.getIva(),Pa.getImpcon(),Pa.getInTur()});
    }

    private Boolean WhiteSpace (){
        return(this.BoxNombre.getText().equals("") || this.BoxImpuCon.getText().equals("") || this.BoxImpuTu.getText().equals("") || this.BoxIVA.getText().equals(""));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JButton BotonCrear;
    private javax.swing.JButton BotonEdit;
    private javax.swing.JButton BotonEliminar;
    private javax.swing.JButton BotonMenu;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JTextField BoxIVA;
    private javax.swing.JTextField BoxImpuCon;
    private javax.swing.JTextField BoxImpuTu;
    private javax.swing.JTextField BoxNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
