/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.javeriana.fdb.view;

import co.edu.javeriana.fdb.parcialdb.controller.logic.DepartamentoBO;
import co.edu.javeriana.fdb.parcialdb.controller.logic.PaisBO;
import co.edu.javeriana.fdb.parcialdb.controller.logic.UsuarioBO;
import co.edu.javeriana.fdb.parcialdb.model.dto.DepartamentoDTO;
import co.edu.javeriana.fdb.parcialdb.model.dto.PaisDTO;
import co.edu.javeriana.fdb.parcialdb.model.dto.UsuarioDTO;

import java.util.List;

/**
 *
 * @author Andres
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    private PaisJPanel paisJPanel;
    private DepartamentoJPanel departamentoJPanel;
    private UsuarioJPanel usuarioJPanel;
    private MenuJPanel menuJPanel;
    private LoggingJPanel loggingJPanel;


    private PaisBO paisBO;
    private DepartamentoBO departamentoBO;
    private UsuarioBO usuarioBO;
    protected UsuarioDTO SesionOn;
    
    public Principal() {
        this.setTitle("Intento de proyecto");
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setVisible(true);
        this.iniciar();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        jLabel2.setText("Inntentarlo");

        jLabel1.setText("Proyecto 3 de Base de datos");

        jLabel3.setText("Karol - Tomas - Andres");

        jLabel4.setText("Java - SQL");

        jButton1.setText("Ir a pais");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ir a departamento");

        jButton3.setBackground(new java.awt.Color(153, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel4)))))
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jButton3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jButton1)
                        .addGap(55, 55, 55)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel2)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1))
                        .addGap(28, 28, 28)))
                .addComponent(jButton3)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //juyu
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.salir();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    private UsuarioDTO getSesionOn(){
        return SesionOn;
    }

    protected void iniciar(){
        this.menuJPanel = new MenuJPanel(this);
        this.menuJPanel.setVisible(true);
        this.add(menuJPanel);
        this.pack();
        this.setLocationRelativeTo(null);
    }

    protected void salir(){
        System.exit(0);
    }
    
    void MenuPais(){
        this.remove(menuJPanel);
        this.paisJPanel = new PaisJPanel(this);
        this.add(paisJPanel);
        this.setLocationRelativeTo(null);
        this.pack();
    }
    
    void MenuUsu(){
        this.remove(menuJPanel);
        this.usuarioJPanel = new UsuarioJPanel(this);
        this.usuarioJPanel.setVisible(true);
        this.add(usuarioJPanel);
        this.setLocationRelativeTo(null);
        this.pack();
    }

    void MenuDepa(){
        this.remove(menuJPanel);
        this.departamentoJPanel = new DepartamentoJPanel(this);
        this.departamentoJPanel.setVisible(true);
        this.add(departamentoJPanel);
        this.setLocationRelativeTo(null);
        this.pack();
    }
    void PaisMenu(){
        this.remove(paisJPanel);
        this.menuJPanel = new MenuJPanel(this);
        this.menuJPanel.setVisible(true);
        this.add(menuJPanel);
        this.setLocationRelativeTo(null);
        this.pack();
    }

    void DepartamentoMenu(){
        this.remove(departamentoJPanel);
        this.menuJPanel = new MenuJPanel(this);
        this.menuJPanel.setVisible(true);
        this.add(menuJPanel);
        this.setLocationRelativeTo(null);
        this.pack();
    }

    void UsuarioMenu(){
        this.remove(usuarioJPanel);
        this.menuJPanel = new MenuJPanel(this);
        this.menuJPanel.setVisible(true);
        this.add(menuJPanel);
        this.setLocationRelativeTo(null);
        this.pack();
    }

    boolean CrearUsuario(UsuarioDTO Usu){
        this.usuarioBO = new UsuarioBO();
        if(this.usuarioBO.Create(Usu)){
            System.out.println("Usuario creado: "+ Usu.toString());
            return true;
        }
        return false;
    }
    //Pais
    boolean CrearPais(PaisDTO Pais){
        this.paisBO = new PaisBO();
        return this.paisBO.Create(Pais);
    }

    List<PaisDTO> findAllPais(){
        this.paisBO = new PaisBO();
        return this.paisBO.findAll();
    }

    PaisDTO findPais(String T){
        this.paisBO = new PaisBO();
        return this.paisBO.findById(T);
    }

    boolean eliminarPais(String T){
        this.paisBO = new PaisBO();
        return this.paisBO.Delete(T);
    }

    boolean editPais(PaisDTO Pais){
        this.paisBO = new PaisBO();
        return this.paisBO.Edit(Pais);
    }
    //Departamento
    boolean CrearDep(DepartamentoDTO Dep){
        this.departamentoBO = new DepartamentoBO();
        return this.departamentoBO.Create(Dep);
    }
    boolean EliminarDep(String D){
        this.departamentoBO = new DepartamentoBO();
        return this.departamentoBO .Delete(D);
    }
    boolean EditDep(DepartamentoDTO Dep){
        this.departamentoBO = new DepartamentoBO();
        return this.departamentoBO.Edit(Dep);
    }
    DepartamentoDTO findDep(String D){
        this.departamentoBO = new DepartamentoBO();
        return this.departamentoBO.findById(D);
    }
    List<DepartamentoDTO> findAllDep(){
        this.departamentoBO = new DepartamentoBO();
        return this.departamentoBO.findByAll();
    }
    //Usuario
    boolean EliminarUsu (String U){
        this.usuarioBO = new UsuarioBO();
        return this.usuarioBO.Delete(U);
    }
    UsuarioDTO findUsu(String U){
        this.usuarioBO = new UsuarioBO();
        return this.usuarioBO.findById(U);
    }

    boolean ChangePass(String Actu, String Nue){
        this.usuarioBO = new UsuarioBO();
        if(this.SesionOn.getContra().equals(Actu)){
            return this.usuarioBO.EditCont(SesionOn,Nue);
        }else{
            return false;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
